misc:
  messages:
    unknown: "&c[*] Hmm, that command doesn't seem to exist, or is missing some arguments"
    no-permission: "&c[*] You don't have permission to use this command"
    info: "&a[*] {1} v&3{2} &7by Medius_Echo"
    reload: "&a[*] All settings for &3{1} &awere reloaded"
    player-error: "&c[*] {1} seems to be hiding, or maybe offline"
    player-only: "&c[*] Sorry, players only"
#
modules:
  #
  motd:
    enabled: true
    line-width: 250
    fallback-motd: "&5❤ &aLivecraft: Online Since 2011 &5❤/n&8- &71.14.4 &8-"
    motds:
      - "&5❤ &71.14.4 - &aLivecraft: Online Since 2011 &5❤/n&fWelcome back &3%player%&f!"
  #
  broadcast:
    enabled: true
    # How long to wait (in minutes) before broadcasting the next message
    interval: 10
    messages:
      - "&a[*] We have a Discord server! https://discord.gg/hQ98qwn"
      - "&a[*] Don't forget to read the /rules!"
      - "&a[*] We have /emotes!"
      - "&a[*] Use @ to ping players!"
      - "&a[*] Sneak right click on a villager to carry them!"
  #
  poke:
    enabled: true
    particle: HEART
    sound:
      id: ENTITY_CHICKEN_EGG
      volume: 1.0
      pitch: 1.0
    # How many seconds to wait before using the poke command again
    command-cooldown: 5
    messages:
      success: "&a[*] You poked {1}"
      opt-in: "&a[*] You can now be poked by {1}"
      opt-out: "&a[*] You are now ignoring pokes from {1}"
      ignoring: "&c[*] You are already ignoring pokes from {1}"
      not-ignoring: "&c[*] You are not ignoring pokes from {1}"
      cooldown: "&c[*] You're too tired to poke"
  #
  emote:
    enable: true
    commands:
      enabled: true
      # Commands that can be parsed for emotes
      whitelisted-commands:
        - "/msg"
        - "/r"
        - "/a"
        - "/pc"
        - "/emsg"
        - "/er"
        - "/me"
        - "/nick"
        - "/enick"
        - "/say"
        - "/bc"
    signs: true
    anvils: true
    emotes:
      hugs: "༼つ◕_◕༽つ"
      shrug: "¯\\_(ツ)_/¯"
      tableflip: "(╯°□°）╯︵ ┻━┻"
      bear: "(ᵔᴥᵔ)"
      teddy: "ʕ•ᴥ•ʔ"
      glasses: "ಠ⌣ಠ"
      frown: "^︵^"
      lenny: "(͡ʖ͡)"
      owo: "(｡◕‿‿◕｡)"
      why: "ლ(ಠ益ಠლ)"
      aww: "(◕‿◕✿)"
      zoidberg: "(/) (°,,°) (/)"
      heart: "\u2764"
      goldstar: "\u272A"
      star: "\u2b50"
      tm: "\u2122"
      check: "\u2714"
      ex: "\u2716"
      music: "♪♫♫♪"
      copyright: "\u00A9"
      rain: "\u2601"
      thunder: "\u2608"
      sun: "\u2600"
      moon: "\u263d"
      snowman: "\u2603"
      snowflake: "\u2744"
      peace: "\u262E"
      flower: "\u273F"
      rose: "\u2698"
      happy: "\u263B"
      sad: "\u2639"
      pencil: "\u270E"
      udq: "¿"
      rip: "\u2620"
      swords: "\u2694"
      square: "\u29c8"
      infinity: "\u221e"
      darrow: "»"
      nuke: "\u2622"
      omega: "\u03A9"
      spade: "\u2660"
      club: "\u2663"
      diamond: "\u2666"
      communism: "\u262D"
      coffee: "\u2615"
      caution: "\u26A0"
      zap: "\u26A1"
      treasure: "\u2718"
      note: "\u266C"
      uwu: "☜ NO"
      chile: "\u2766"
      coin: "\u23FC"
      coin1: "\u26C0"
      coins1: "\u26C1"
      coin2: "\u26C2"
      coins2: "\u26C3"
      acorn: "\u26E8"
      flag: "\u2691"
      pick: "\u26cf"
      fire: "\u2632"
      anchor: "\u2693"
      left: "\u2190"
      up: "\u2191"
      right: "\u2192"
      down: "\u2193"
      pleft: "\u23F4"
      pup: "\u23F6"
      pright: "\u23F5"
      pdown: "\u23F7"
      power: "\u23FB"
      lamda: "\u03bb"
      male: "\u2642"
      female: "\u2640"
      hry: "\u20B4"
      euro: "\u20AC"
      bullet: "\u2022"
      dice1: "\u2680"
      dice2: "\u2681"
      dice3: "\u2682"
      dice4: "\u2683"
      dice5: "\u2684"
      dice6: "\u2685"
      1: "\u2460"
      2: "\u2461"
      3: "\u2462"
      4: "\u2463"
      5: "\u2464"
      6: "\u2465"
      7: "\u2466"
      8: "\u2467"
      9: "\u2468"
      10: "\u2469"
      n1: "\u278A"
      n2: "\u278B"
      n3: "\u278C"
      n4: "\u278D"
      n5: "\u278E"
      n6: "\u278F"
      n7: "\u2790"
      n8: "\u2791"
      n9: "\u2792"
      n10: "\u2793"
      0: "\u24EA"
      a: "\u24B6"
      b: "\u24B7"
      c: "\u24B8"
      d: "\u24B9"
      e: "\u24BA"
      f: "\u24BB"
      g: "\u24BC"
      h: "\u24BD"
      i: "\u24BE"
      j: "\u24BF"
      k: "\u24C0"
      l: "\u24C1"
      m: "\u24C2"
      n: "\u24C3"
      o: "\u24C4"
      p: "\u24C5"
      q: "\u24C6"
      r: "\u24C7"
      s: "\u24C8"
      t: "\u24C9"
      u: "\u24CA"
      v: "\u24CB"
      w: "\u24CC"
      x: "\u24CD"
      y: "\u24CE"
      z: "\u24CF"
      test: "\u0296"
      black: "\u00A70"
      darkblue: "\u00A71"
      darkgreen: "\u00A72"
      darkaqua: "\u00A73"
      darkred: "\u00A74"
      darkpurple: "\u00A75"
      gold: "\u00A76"
      gray: "\u00A77"
      darkgray: "\u00A78"
      blue: "\u00A79"
      green: "\u00A7a"
      aqua: "\u00A7b"
      red: "\u00A7c"
      lightpurple: "\u00A7d"
      yellow: "\u00A7e"
      white: "\u00A7f"
      magic: "\u00A7k"
      bold: "\u00A7l"
      strike: "\u00A7m"
      underline: "\u00A7n"
      italic: "\u00A7o"
      reset: "\u00A7r"
  #
  markdown:
    enabled: true
    signs: true
    anvils: true
    # Apply markdown to commands
    commands:
      enabled: true
      # Commands that can be parsed for markdown
      whitelisted-commands:
        - "/msg"
        - "/r"
        - "/a"
        - "/pc"
        - "/emsg"
        - "/er"
        - "/me"
        - "/nick"
        - "/enick"
        - "/say"
    formats:
      bold-italic:
        regex: "\\*{3}(.*?)\\*{3}"
        replacement: "&l&o{1}&r"
        priority: 1
      bold:
        regex: "\\*{2}(.*?)\\*{2}"
        replacement: "&l{1}&r"
        priority: 5
      italic:
        regex: "\\*(.*?)\\*"
        replacement: "&o{1}&r"
        priority: 10
      underline:
        regex: "__(.*?)__"
        replacement: "&n{1}&r"
        priority: 15
      italic-alternate:
        regex: "\\b_(.*?)_\\b"
        replacement: "&o{1}&r"
        priority: 20
      strikethrough:
        regex: "~~(.*?)~~"
        replacement: "&m{1}&r"
        priority: 25
  #
  ping:
    enabled: true
    player-highlight: "&3{1}&r"
    include-nicknames: true
    sound:
      id: BLOCK_NOTE_BLOCK_BIT
      volume: 1.0
      pitch: 1.0
    particle: VILLAGER_HAPPY
    special-pings:
      random:
        enabled: true
        highlight: "&5{1}&r"
        aliases:
          - someone
          - anyone
    groups:
      enabled: true
      groups:
        staff:
          highlight: "&c{1}&r"
          aliases:
            - staff
        admin:
          highlight: "&c{1}&r"
          aliases:
            - admin
            - administrator
        global:
          highlight: "&c{1}&r"
          aliases:
            - everyone
            - here
    commands:
      enabled: true
      whitelist:
        - "/say"
        - "/bc"
        - "/a"
  book:
    enabled: true
    messages:
      update-error: "&c[*] You must be holding a writable book to save"
      save-error: "&c[*] There was an issue saving this book, please try again"
      save-success: "&a[*] Saved {1} book successfully"
      update-success: "&a[*] Updated rule book"
      parse-error: "&c[*] You must be holding a Book & Quill to parse"
      parsed: "&a[*] Book was updated"
      missing: "&c[*] Unable to find the book '&7{1}&c'"
      confirm: "&a[*] type &7/lc book save {1} &aagain to save this book"
      delete: "&a[*] Book '&7{1}&a' was deleted"
      exists: "&c[*] The book '&7{1}&c' already exists"
      open-permission: "&c[*] You don't have permission to open this book"  #
  sleepvote:
    enabled: true
    worlds:
      - livecraft
      - livecraft_1_14
    # Percentage of players needed in a given world to skip the night
    sleep-percentage: 0.5
    # Players with the permission 'lce.sleepvote.ignore' will not count towards the sleep goal
    ignore-staff: false
    # Disable this if you want sleepvote to work in thunderstorms
    check-weather: true
    # Broadcast the wake up message only to players that were sleeping in a given world
    broadcast-wake-up-to-sleeping-players-only: false
    messages:
      # {1}: The name of the player
      # {2}: How many are currently sleeping
      # {3}: How many need to sleep
      sleeping: "&a[*] {1} &awants to sleep! &7(&a{2}/{3}&7)"
      waking: "&a[*] Wakey wakey, eggs and bakey"
      thunder: "&a[*] {1} &awants to skip the storm! &7(&a{2}/{3}&7)"